#!/bin/bash

from_path=$(dirname "$0")
zshrc_path=$(realpath "$from_path/zshrc")

install -v -m 400 "$zshrc_path" "${HOME}/.zshrc" || exit 1
git clone --depth=1 https://github.com/romkatv/powerlevel10k.git ${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}/themes/powerlevel10k

exit 0
